=head1 NAME

Web::DateTime - Date and time for Web

=head1 SYNOPSIS

  use Web::DateTime;
  $dt = Web::DateTime->new->parse_global_date_and_time_string ($value);
  warn $dt->to_unix_integer;

=head1 DESCRIPTION

The C<Web::DateTime> module has parsers and serializers of various
date and time representations used in Web.

=head1 METHODS

XXX

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2008-2013 Wakaba <wakaba@suikawiki.org>.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
